var searchData=
[
  ['vagtcollection',['VagtCollection',['../class__1aarsproeve_1_1_view_model_1_1_vagtplan_view_model.html#ae7053bf4cbd85b49e181e72586909c20',1,'_1aarsproeve::ViewModel::VagtplanViewModel']]],
  ['vagtcollectionsarray',['VagtCollectionsArray',['../class__1aarsproeve_1_1_model_1_1_vagtplan_singleton.html#a1517f87a41a08159dbb44fe024207b70',1,'_1aarsproeve::Model::VagtplanSingleton']]],
  ['vagter',['Vagter',['../class_w_s1aarsproeve_1_1_vagter.html',1,'WS1aarsproeve']]],
  ['vagter',['Vagter',['../class__1aarsproeve_web_service_1_1_vagter.html',1,'_1aarsproeveWebService']]],
  ['vagterliste',['VagterListe',['../class__1aarsproeve_1_1_model_1_1_vagtplan_singleton.html#a290144ecbd07ab56a48bb4f8555ac6b1',1,'_1aarsproeve::Model::VagtplanSingleton']]],
  ['vagterscontroller',['VagtersController',['../class__1aarsproeve_web_service_1_1_controllers_1_1_vagters_controller.html',1,'_1aarsproeveWebService::Controllers']]],
  ['vagterscontroller',['VagtersController',['../class_w_s1aarsproeve_1_1_controllers_1_1_vagters_controller.html',1,'WS1aarsproeve::Controllers']]],
  ['vagtersviewcontroller',['VagtersViewController',['../class__1aarsproeve_web_service_1_1_controllers_1_1_vagters_view_controller.html',1,'_1aarsproeveWebService::Controllers']]],
  ['vagtertests',['VagterTests',['../class__1aarsproeve_tests_1_1_vagter_tests.html',1,'_1aarsproeveTests']]],
  ['vagthandler',['VagtHandler',['../class__1aarsproeve_1_1_view_model_1_1_vagtplan_view_model.html#acdf9517320f79372aaed5c644df493aa',1,'_1aarsproeve.ViewModel.VagtplanViewModel.VagtHandler()'],['../class__1aarsproeve_1_1_handler_1_1_vagt_handler.html#a030580ed58226bf1741303da667a7954',1,'_1aarsproeve.Handler.VagtHandler.VagtHandler()']]],
  ['vagthandler',['VagtHandler',['../class__1aarsproeve_1_1_handler_1_1_vagt_handler.html',1,'_1aarsproeve::Handler']]],
  ['vagtid',['VagtId',['../class__1aarsproeve_1_1_model_1_1_anmodning_model.html#a3cf77af016a0edfd3ba87c9ed58971e0',1,'_1aarsproeve.Model.AnmodningModel.VagtId()'],['../class__1aarsproeve_1_1_model_1_1_vagt_model.html#a1ca9a9a8b8457d405761ca9b5d35152c',1,'_1aarsproeve.Model.VagtModel.VagtId()']]],
  ['vagtmodel',['VagtModel',['../class__1aarsproeve_1_1_model_1_1_vagt_model.html',1,'_1aarsproeve::Model']]],
  ['vagtmodel',['VagtModel',['../class__1aarsproeve_1_1_model_1_1_vagt_model.html#a3713a9d3329ba8c9d0f9af50d6c53007',1,'_1aarsproeve.Model.VagtModel.VagtModel()'],['../class__1aarsproeve_1_1_model_1_1_vagt_model.html#aa06ec8a6c5c234eae1bcb10f2630911e',1,'_1aarsproeve.Model.VagtModel.VagtModel(TimeSpan starttidspunkt, TimeSpan sluttidspunkt, int ugenummer, Ugedage ugedag, Ansatte ansat)'],['../class__1aarsproeve_1_1_model_1_1_vagt_model.html#a6e840b6f3f533e963bd607fb36640eb6',1,'_1aarsproeve.Model.VagtModel.VagtModel(int vagtId, TimeSpan starttidspunkt, TimeSpan sluttidspunkt, int ugenummer, int ugedagId, string brugernavn)']]],
  ['vagtmodel',['VagtModel',['../class_w_s1aarsproeve_1_1_vagt_model.html',1,'WS1aarsproeve']]],
  ['vagtmodelscontroller',['VagtModelsController',['../class_w_s1aarsproeve_1_1_controllers_1_1_vagt_models_controller.html',1,'WS1aarsproeve::Controllers']]],
  ['vagtplan',['Vagtplan',['../class__1aarsproeve_1_1_view_1_1_vagtplan.html',1,'_1aarsproeve::View']]],
  ['vagtplansingleton',['VagtplanSingleton',['../class__1aarsproeve_1_1_model_1_1_vagtplan_singleton.html',1,'_1aarsproeve::Model']]],
  ['vagtplanview',['VagtplanView',['../class__1aarsproeve_web_service_1_1_vagtplan_view.html',1,'_1aarsproeveWebService']]],
  ['vagtplanviewmodel',['VagtplanViewModel',['../class__1aarsproeve_1_1_handler_1_1_vagt_handler.html#ac7a38ad84077edb90a6dc695e05c756e',1,'_1aarsproeve.Handler.VagtHandler.VagtplanViewModel()'],['../class__1aarsproeve_1_1_view_model_1_1_vagtplan_view_model.html#a9cd0dee8f4da04199f5fd0dde63cbcda',1,'_1aarsproeve.ViewModel.VagtplanViewModel.VagtplanViewModel()']]],
  ['vagtplanviewmodel',['VagtplanViewModel',['../class__1aarsproeve_1_1_view_model_1_1_vagtplan_view_model.html',1,'_1aarsproeve::ViewModel']]],
  ['valueproviderattribute',['ValueProviderAttribute',['../class_value_provider_attribute.html',1,'']]],
  ['valuescontroller',['ValuesController',['../class_w_s1aarsproeve_1_1_controllers_1_1_values_controller.html',1,'WS1aarsproeve::Controllers']]],
  ['viewcontext',['ViewContext',['../class_w_s1aarsproeve_1_1_view_context.html',1,'WS1aarsproeve']]]
];
